
name: lwc-language-server
description: Language Server for Lightning Web Components.
homepage: https://github.com/forcedotcom/lightning-language-server/
licenses:
  - BSD-3-Clause
languages:
  - HTML
  - JavaScript
categories:
  - LSP
source:
  id: pkg:npm/@salesforce/lwc-language-server@v4.7.3
schemas:
  lsp: vscode:https://raw.githubusercontent.com/forcedotcom/lightning-language-server/main/packages/lwc-language-server/package.json
bin:
  lwc-language-server: npm:lwc-language-server
